### ISSUE TITLE
commands not working

### ISSUE THREAD

**Issue by TahaAzhar36** [NullCode13/NullRAT#10]
when ever i type any command like /getip or any other nothing happens bot is online and notif also come of rat injected

**Comment by NullCode1337** [comment]
sorry to hear. Let me test NullRAT myself

**Comment by NullCode1337** [comment]
you did smth wrong
![image](https://user-images.githubusercontent.com/70959549/149372630-d3251167-058f-40af-b88e-0c6f2ca08b44.png)
lol. check all your required variables

**Comment by NullCode1337** [comment]
2 days have passed, no replies.

closed. for further problems, reply to this thread again
