### ISSUE TITLE
How to use commands

### ISSUE THREAD

**Issue by fabwaseem** [NullCode13/NullRAT#11]
How to use commands not working with slash please list commands

**Comment by NullCode1337** [comment]
ok ok fine. I'll make a video tutorial for NullRAT. gosh

**Comment by NullCode1337** [comment]
`Getting Variables.md`

Read it, get all variables, and use your brain. (it's as ez as putting those vars I'm compiler)

**Comment by NullCode1337** [comment]
any more issues, add me on discord: NullCode1337#1638
