### ISSUE TITLE
Maybe Add 2 Modes Slash Commands And prefix 

### ISSUE THREAD

**Issue by Catchii** [NullCode13/NullRAT#12]
all bots dont have slash commands rn atleast i cant get mine to work 

would be nice if u could add an config or sum or an setting in compiler where u can choose between prefix and slash cmds

im prob to retarded to make it work..

**Comment by NullCode1337** [comment]
how does it not work? have you bothered reading `Getting Variables.md` btw

**Comment by NullCode1337** [comment]
also if i was going to add a prefix mode, I'd need to maintain 2 rats, something which I'm not willing to do atm. if anyone wants to, sure

**Comment by Catchii** [comment]
I followed everything in variables the message get sended when the rat connects the slash commands just won't work

**Comment by NullCode1337** [comment]
mhm, hit me up on Discord: NullCode1337#1638

**Comment by Catchii** [comment]
added Catchii#0001

**Comment by Catchii** [comment]
0001

**Comment by NullCode1337** [comment]
fixed in discord
