### ISSUE TITLE
doesnt matter what settings i use always this error when ran

### ISSUE THREAD

**Issue by Epik123** [NullCode13/NullRAT#18]
![image](https://user-images.githubusercontent.com/85456368/151641906-e4588c38-bdc4-4785-b27d-19b883cba56e.png)

**Comment by NullCode1337** [comment]
thanks for the pointer,
**uninstall every single discord.py libraries**, and run the dependencies installer again

that will fix your issue
i will be adding this to the dependencies installer so that there are no more problems

**Comment by NullCode1337** [comment]
any further issues, feel free to reply
