### ISSUE TITLE
[Finished] Startup

### ISSUE THREAD

**Issue by serialame** [NullCode13/NullRAT#2]
adding to startup would be nice, tried myself couldnt get it to work

**Comment by NullCode1337** [comment]
You mean a command that automatically adds file to startup?
Hm could be fun to implement

Might break AV detection tho

**Comment by NullCode1337** [comment]
Command added: [https://github.com/NullCode13/NullRAT/commit/5d4b192e672fa19c1dd4b88a17f82a81df680e65](https://github.com/NullCode13/NullRAT/commit/5d4b192e672fa19c1dd4b88a17f82a81df680e65)

Release will be uploaded once I make sure everything's fine

Closed.
