### ISSUE TITLE
Error finishing build

### ISSUE THREAD

**Issue by atlaslolz** [NullCode13/NullRAT#22]
https://prnt.sc/26wndis The exe isnt showing or installing, even though it says its been done. Also when I tried using a un-obfuscated vers, it gave me this https://prnt.sc/26wngg9 , i checked my PATH to see if anythings fucked and i didnt see anything wrong but just to be safe i added hella paths, tried again and still nothing https://prnt.sc/26wnhhv maybe im dumb i dunno

**Comment by NullCode1337** [comment]
![image](https://user-images.githubusercontent.com/70959549/154204559-150f1a46-eb99-4830-9211-72170db04c9f.png)
don't add this comma, check if the issue is fixed after that

**Comment by NullCode1337** [comment]
sorry accidentally closed, report if it still works/doesn't work

**Comment by atlaslolz** [comment]
> ![image](https://user-images.githubusercontent.com/70959549/154204559-150f1a46-eb99-4830-9211-72170db04c9f.png) don't add this comma, check if the issue is fixed after that

tried that https://prnt.sc/26wpu21 it "finished" building very quickly and didnt output a file, do you maybe have discord so we could chat better?

**Comment by NullCode1337** [comment]
> > ![image](https://user-images.githubusercontent.com/70959549/154204559-150f1a46-eb99-4830-9211-72170db04c9f.png) don't add this comma, check if the issue is fixed after that
> 
> tried that https://prnt.sc/26wpu21 it "finished" building very quickly and didnt output a file, do you maybe have discord so we could chat better?

NullCode1337#1638

**Comment by ghost** [comment]
@atlaslolz Update to [v6.2](https://github.com/NullCode1337/NullRAT/releases/tag/v6.2). This issue just got fixed in it.

**Comment by atlaslolz** [comment]
@NullCode1337 i added ur discord but 
Traceback (most recent call last):
  File "<dist\obf\RAT.py>", line 3, in <module>
  File "<frozen RAT>", line 8, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "discord\__init__.py", line 33, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "discord\commands\__init__.py", line 26, in <module>
ModuleNotFoundError: No module named 'discord.commands.__init__.context'
