### ISSUE TITLE
add commands list command

### ISSUE THREAD

**Issue by pancak3boy** [NullCode13/NullRAT#26]
add a command which shows every command so I can run the command to see the commands

**Comment by pancak3boy** [comment]
cause u had it before but now It no exist

**Comment by ghost** [comment]
> add a command which shows every command so I can run the command to see the commands

Slash commands don't require this, they get listed as available after adding a `/` at the first character of the message.

**Comment by NullCode1337** [comment]
^^^^^^^^^^^^
