### ISSUE TITLE
[Problem] Temp Folder?

### ISSUE THREAD

**Issue by heyitshestia** [NullCode13/NullRAT#27]
![image](https://user-images.githubusercontent.com/78128225/159813012-585f0616-5cac-4f8f-a4a9-e0cd737fb285.png)

 So i got about this far. It compiles nothing if i run it like this. When i add an empty temp folder to the null-release folder it does compile the exe, but does nothing when i run it. Running it in IDLE shows that nothing is happening either. Am i missing something????

**Comment by heyitshestia** [comment]
I should add that i do get the "Null-RAT started on xxxxxx" in my specified discord channel when i start it after compiling with the added empty temp folder. And the RAT-patched shows a ton of missing modules if that means anything.

**Comment by NullCode1337** [comment]
> ![image](https://user-images.githubusercontent.com/78128225/159813012-585f0616-5cac-4f8f-a4a9-e0cd737fb285.png)
> 
> So i got about this far. It compiles nothing if i run it like this. When i add an empty temp folder to the null-release folder it does compile the exe, but does nothing when i run it. Running it in IDLE shows that nothing is happening either. Am i missing something????

seems like an issue with the compiler
ill ask out C# expert @usrDottik to help pls

**Comment by ghost** [comment]
The error is because the compiler failed to delete a directory, I programmed those that are assured to be there, strange, ignore it, it won't cause an issue, I will add a try catch block to catch the exception, regarding Nullrat, @NullCode1337

**Comment by NullCode1337** [comment]
we'll come back to nullrat after compiler is fixed :trollface:

**Comment by ghost** [comment]
> we'll come back to nullrat after compiler is fixed :trollface: 

._.

**Comment by heyitshestia** [comment]
Sooooo... that still doesn't explain why the compiled exe isn't working or not compiling at all. Or it does and it went over my head.

**Comment by NullCode1337** [comment]
> Sooooo... that still doesn't explain why the compiled exe isn't working or not compiling at all. Or it does and it went over my head.

if the rat compiles, and it doesn't work, then theres a problem with the variables OR the bot invite link scope
if the rat doesn't compile at all, it's a problem with the compiler and Dottik will fix it

**Comment by ghost** [comment]
> Sooooo... that still doesn't explain why the compiled exe isn't working or not compiling at all. Or it does and it went over my head.

Hmm, I tried reworking the compiler just like I did with the Dependency installer in 869c2dfd24c07785d5e578ec94b7844003449482 , but PyArmor refused to create the spec file correctly, so I'm having to do some magic, else it will just be a variable setter

**Comment by ghost** [comment]
NullRAT Compiler has been discontinued, on next release the Batch Compiler will be back in all it's glory.
1058ca9598acfc5b943ef2782f915cfb3af13f55
