### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by bladee23232** [NullCode13/NullRAT#28]
I followed all of the instructions and it gave me this error before closing instantly.

![image](https://user-images.githubusercontent.com/103006214/161647725-9c8c13e1-8e92-45f0-8a60-a7de493f7ba6.png)

**Comment by NullCode1337** [comment]
pyarmor not in path
check if pip folder is in path, and run the dependencies installer

**Comment by ghost** [comment]
@bladee23232 Add the following Path to your PATH environment variable

`C:\Users\17814\AppData\Roaming\Python\Python310\Scripts`

This is due that you require to set the user scripts folder, Modify the `Python310` if your Python version is NOT 3.10

**Comment by NullCode1337** [comment]
damn do i need to add @usrDottik 's comment as a FAQ
everyone has a problem with it
