### ISSUE TITLE
Random Connections

### ISSUE THREAD

**Issue by serialame** [NullCode13/NullRAT#3]
I havent given out the compiled file to anyone, I tested it with VT, but I'm getting random connections on the webhook which have random ips and stuff
![Screenshot_2021-07-11-14-34-47-21_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/58895443/125195327-72242100-e255-11eb-8ca2-b60e7f2049e9.jpg)

**Comment by NullCode13** [comment]
WHAT THE HELL
WHY WOULD YOU SEND IT OVER TO VIRUSTOTAL

THE SECURITY RESEARCHERS ARE PROBABLY RUNNING THE FILE RIGHT NOW
_COME ON MAN_

**Comment by NullCode1337** [comment]
Rant over
Your problem: Other security researchers are running the file, because you uploaded it to VirusTotal
Hence, the random IPs

Closed.
