### ISSUE TITLE
[Issue] Compiler not working

### ISSUE THREAD

**Issue by Jamster707** [NullCode13/NullRAT#30]
when trying to compile it, it says:

![Capture](https://user-images.githubusercontent.com/78559406/163051030-8f80013a-2c9a-485b-bf5f-c4ed379957cd.PNG)

it still makes a file, but the file doesn't do anything when opened

**Comment by ghost** [comment]
as I said back in #27

> The error is because the compiler failed to delete a directory, I programmed those that are assured to be there, strange, ignore it, it won't cause an issue, I will add a try catch block to catch the exception

I've not done it since I've tried to make the compiler code cleaner than it's now, that error is normal, since it fails to delete the folder. If NullRAT Compiler compiled the RAT in practically nothing, then it's broken. If such case presents, please, notify me.

**Comment by Jamster707** [comment]
> 

what do you mean by "compiled the rat in practically nothing"?

**Comment by Jamster707** [comment]
> as I said back in #27
> 
> > The error is because the compiler failed to delete a directory, I programmed those that are assured to be there, strange, ignore it, it won't cause an issue, I will add a try catch block to catch the exception
> 
> I've not done it since I've tried to make the compiler code cleaner than it's now, that error is normal, since it fails to delete the folder. If NullRAT Compiler compiled the RAT in practically nothing, then it's broken. If such case presents, please, notify me.

what do you mean by "compiled the RAT in practically nothing"?

**Comment by ghost** [comment]
I mean that if it compiled in a very short time span, then it's likely broken, this might happen because PyArmor and/or PyInstaller refuse to work, as such the compilation will go real fast in a matter of less than 5 seconds, which is an indicator that it didn't compile

**Comment by Jamster707** [comment]
> I mean that if it compiled in a very short time span, then it's likely broken, this might happen because PyArmor and/or PyInstaller refuse to work, as such the compilation will go real fast in a matter of less than 5 seconds, which is an indicator that it didn't compile

it doesn't do that, but it does create a file that does nothing when opened, and im not sure what i'm doing wrong

**Comment by ghost** [comment]
> > I mean that if it compiled in a very short time span, then it's likely broken, this might happen because PyArmor and/or PyInstaller refuse to work, as such the compilation will go real fast in a matter of less than 5 seconds, which is an indicator that it didn't compile
> 
> it doesn't do that, but it does create a file that does nothing when opened, and im not sure what i'm doing wrong

Huh, then check if you declared the variables correctly, token, server id, notification channel id, when you execute the RAT it should send a notification to the Discord server you prepared, if you are still lost, and/or don't know what to do, I recommend you check out [this tutorial that NullCode made](https://youtu.be/G8CsgWYiwWI), you may want to tune volume down a bit for it.

**Comment by NullCode1337** [comment]
>you may want to tune volume down a bit for it.

LMAO

**Comment by LilCrabby** [comment]
> as I said back in #27
> 
> > The error is because the compiler failed to delete a directory, I programmed those that are assured to be there, strange, ignore it, it won't cause an issue, I will add a try catch block to catch the exception
> 
> I've not done it since I've tried to make the compiler code cleaner than it's now, that error is normal, since it fails to delete the folder. If NullRAT Compiler compiled the RAT in practically nothing, then it's broken. If such case presents, please, notify me.

This is what happens to me i get this error message : 
![image](https://user-images.githubusercontent.com/47627728/163655646-cd213cc2-e4c0-4488-98f1-f426375a7141.png)

and it would just close without making the file like it did in @NullCode1337 's video.

**Comment by ghost** [comment]
> > as I said back in #27
> > > The error is because the compiler failed to delete a directory, I programmed those that are assured to be there, strange, ignore it, it won't cause an issue, I will add a try catch block to catch the exception
> > 
> > 
> > I've not done it since I've tried to make the compiler code cleaner than it's now, that error is normal, since it fails to delete the folder. If NullRAT Compiler compiled the RAT in practically nothing, then it's broken. If such case presents, please, notify me.
> 
> This is what happens to me i get this error message : ![image](https://user-images.githubusercontent.com/47627728/163655646-cd213cc2-e4c0-4488-98f1-f426375a7141.png)
> 
> and it would just close without making the file like it did in @NullCode1337 's video.

Did you add the folder NullCode added to path and signed out as the tutorial said?

**Comment by LilCrabby** [comment]
> > > as I said back in #27
> > > > The error is because the compiler failed to delete a directory, I programmed those that are assured to be there, strange, ignore it, it won't cause an issue, I will add a try catch block to catch the exception
> > > 
> > > 
> > > I've not done it since I've tried to make the compiler code cleaner than it's now, that error is normal, since it fails to delete the folder. If NullRAT Compiler compiled the RAT in practically nothing, then it's broken. If such case presents, please, notify me.
> > 
> > 
> > This is what happens to me i get this error message : ![image](https://user-images.githubusercontent.com/47627728/163655646-cd213cc2-e4c0-4488-98f1-f426375a7141.png)
> > and it would just close without making the file like it did in @NullCode1337 's video.
> 
> Did you add the folder NullCode added to path and signed out as the tutorial said?

I did add the folder and after i just restarted my pc instead of signing out.

**Comment by NullCode1337** [comment]
send the **full** directory you added to path
also did you run dependencies installer after adding to path, or before? in the video I do it after

**Comment by LilCrabby** [comment]
> send the **full** directory you added to path also did you run dependencies installer after adding to path, or before? in the video I do it after

So i got it to work 1 step further, apparently for some reason there were 2 different paths for an install of python with the \scripts folder. So i tried to add the other path and it worked but now i have this message :
![image](https://user-images.githubusercontent.com/47627728/163712666-6813f299-28d3-46bf-9efe-de9fd0eeac4c.png)

But when i look at the folder it has no RAT.exe in it.

The only one that works it when i select NO for all the build options so without (Custom icon, Comprression and without Obfuscating) that  is the only way i get the working exe.

few points of notice.
1) i did run the NullRAT Dependencies again to be sure.
2) i selected yes for al the build options
3) if i select any of the build options it compiles in less then 5 seconds as @usrDottik mentioned **[here](https://github.com/NullCode1337/NullRAT/issues/30#issuecomment-1098070804)** and i get the message in the screenshot.

**Comment by ghost** [comment]
> > send the **full** directory you added to path also did you run dependencies installer after adding to path, or before? in the video I do it after
> 
> So i got it to work 1 step further, apparently for some reason there were 2 different paths for an install of python with the \scripts folder. So i tried to add the other path and it worked but now i have this message : ![image](https://user-images.githubusercontent.com/47627728/163712666-6813f299-28d3-46bf-9efe-de9fd0eeac4c.png)
> 
> But when i look at the folder it has no RAT.exe in it.
> 
> The only one that works it when i select NO for all the build options so without (Custom icon, Comprression and without Obfuscating) that is the only way i get the working exe.
> 
> few points of notice.
> 
> 1. i did run the NullRAT Dependencies again to be sure.
> 2. i selected yes for al the build options
> 3. if i select any of the build options it compiles in less then 5 seconds as @usrDottik mentioned **[here](https://github.com/NullCode1337/NullRAT/issues/30#issuecomment-1098070804)** and i get the message in the screenshot.

Damn it, NullRAT Compiler seems to be broken. I guess we will bring back the batch file, and the Compiler will just be a variable setter for NullRAT, unless I change a bit how the compilation works with Obfuscation, testing the code through PowerShell or CMD will compile it right away, I have my suspicion why (It's regarding spec files btw)

**Comment by LilCrabby** [comment]
> > > send the **full** directory you added to path also did you run dependencies installer after adding to path, or before? in the video I do it after
> > 
> > 
> > So i got it to work 1 step further, apparently for some reason there were 2 different paths for an install of python with the \scripts folder. So i tried to add the other path and it worked but now i have this message : ![image](https://user-images.githubusercontent.com/47627728/163712666-6813f299-28d3-46bf-9efe-de9fd0eeac4c.png)
> > But when i look at the folder it has no RAT.exe in it.
> > The only one that works it when i select NO for all the build options so without (Custom icon, Comprression and without Obfuscating) that is the only way i get the working exe.
> > few points of notice.
> > 
> > 1. i did run the NullRAT Dependencies again to be sure.
> > 2. i selected yes for al the build options
> > 3. if i select any of the build options it compiles in less then 5 seconds as @usrDottik mentioned **[here](https://github.com/NullCode1337/NullRAT/issues/30#issuecomment-1098070804)** and i get the message in the screenshot.
> 
> Damn it, NullRAT Compiler seems to be broken. I guess we will bring back the batch file, and the Compiler will just be a variable setter for NullRAT, unless I change a bit how the compilation works with Obfuscation, testing the code through PowerShell or CMD will compile it right away, I have my suspicion why (It's regarding spec files btw)

if i can help with any more info you need or anything let me know

**Comment by NullCode1337** [comment]
alright
so since the compiler is broken, I'm gonna bring back the batch one (except **there'll be a twist**)

please hold on for a moment, and thanks for the intel!

**Comment by ghost** [comment]
NullRAT Compiler, may now rest in peace.
in commit 1058ca9598acfc5b943ef2782f915cfb3af13f55 I removed Compiler, so now @NullCode1337, you need to create your batch magic

**Comment by NullCode1337** [comment]
please try out new release of NullRAT, it has fixed compiler
https://github.com/NullCode1337/NullRAT/releases/download/v8.0/NullRAT-Release-x86.7z

**Comment by kakakas33** [comment]
INFO     ==================== Run command ====================
98 INFO: PyInstaller: 5.0
99 INFO: Python: 3.10.4
112 INFO: Platform: Windows-10-10.0.20348-SP0
option(s) not allowed:
  --onedir/--onefile
  --console/--nowindowed/--windowed/--noconsole
makespec options not valid when a .spec file is given
ERROR    Run command failed
The system cannot find the file specified.
Press any key to continue . . .

**Comment by LilCrabby** [comment]
> please try out new release of NullRAT, it has fixed compiler https://github.com/NullCode1337/NullRAT/releases/download/v8.0/NullRAT-Release-x86.7z

@NullCode1337 cant seem to get it to work (i might not have done it right), should i run the files in order 1,2,3? or is it just 1 and 3 ? 

![image](https://user-images.githubusercontent.com/47627728/164990198-ab0bc49d-d7d4-4c20-a990-1dfd960e716b.png)

**Comment by NullCode1337** [comment]
Yup. 1,2,3

**Comment by LilCrabby** [comment]
> Yup. 1,2,3

so i ran nr 1 that went fine, then i ran 2 and  it said that the  source code needed to be updated and asked if i wanted to update(i chose yes) and then i filled in the info.  after filing in the info i think it said something like updating variables and it closed that window. Last i opened 3 and used yes on all except the custom image  and after confirming the options the window closed  but nothing changed in the folder

i tried all the options on separately but it did not work for me, i also tried running it as admin but that did not change anything for me.

i also tried without updating the source but that also didn't work for me.

**Comment by NullCode1337** [comment]
yeah just hold on. I've noticed a lot of problems in the code dottik manages
im deleting all of them and rewriting it in batch

oh btw, dont use the microsoft store version of python, pwease

**Comment by NullCode1337** [comment]
@LilCrabby @kakakas33 @Jamster707 try out the new new 7.5 release lmao

**Comment by LilCrabby** [comment]
> @LilCrabby @kakakas33 @Jamster707 try out the new new 7.5 release lmao

i might be doing something wrong, After running al 3 i did get an new file named (Variables.py) after  running the 2nd file but after i run the 3rd one nothing changed in the files.

**Comment by NullCode1337** [comment]
yeah you're probably doing something wrong at this point

nullrat works on both my vm and main host

**Comment by NullCode1337** [comment]
it is, and as such I'm making my own
well I've already finished making one

**Comment by ghost** [comment]
> yeah just hold on. I've noticed a lot of problems in the code dottik manages im deleting all of them and rewriting it in batch
> 
> oh btw, dont use the microsoft store version of python, pwease

The compiler was having problems, I removed it entirely, now it's up to you Null

**Comment by NullCode1337** [comment]
> > yeah just hold on. I've noticed a lot of problems in the code dottik manages im deleting all of them and rewriting it in batch
> > oh btw, dont use the microsoft store version of python, pwease
> 
> The compiler was having problems, I removed it entirely, now it's up to you Null

your depinst code was also broken, it wasnt installing pyinstaller and stuff
really messed up, so i ended up removing it entirely

**Comment by ghost** [comment]
> > > yeah just hold on. I've noticed a lot of problems in the code dottik manages im deleting all of them and rewriting it in batch
> > > oh btw, dont use the microsoft store version of python, pwease
> > 
> > 
> > The compiler was having problems, I removed it entirely, now it's up to you Null
> 
> your depinst code was also broken, it wasnt installing pyinstaller and stuff really messed up, so i ended up removing it entirely

But if you want to replace all tools, do it, less work for me :p

**Comment by NullCode1337** [comment]
no work for you :P no C# code exists anymore

**Comment by ghost** [comment]
> no work for you :P no C# code exists anymore

😎 Perfect.

**Comment by ghost** [comment]
So, NullRAT Tools are no more, now u do ur job and code all, imma remove the current src for them

**Comment by NullCode1337** [comment]
yes

anyways guys i can't sleep at night if nobody tells me NullRAT works
please test!!!

**Comment by NullCode1337** [comment]
![image](https://catchii.wtf/images/catchii/57279/image.png)
a friend got this weird asf "vmware" error wtf. does anyone have ideas as to what it is

oh btw, this is my pc: 
![image](https://user-images.githubusercontent.com/70959549/165111784-6e0808d5-1521-44f1-9e09-fcfbf0893fca.png)

**Comment by NullCode1337** [comment]
dont close it, others might still have problems

**Comment by mfn003** [comment]
> ![image](https://camo.githubusercontent.com/bf29e593057adaabb911342559ba9dc5952407e49c6454c2abf356d0d979f7ff/68747470733a2f2f636174636869692e7774662f696d616765732f636174636869692f35373237392f696d6167652e706e67) a friend got this weird asf "vmware" error wtf. does anyone have ideas as to what it is
> 
> oh btw, this is my pc: ![image](https://user-images.githubusercontent.com/70959549/165111784-6e0808d5-1521-44f1-9e09-fcfbf0893fca.png)

maybe path is being parsed wrong? idk im not sure.

**Comment by NullCode1337** [comment]
> > ![image](https://camo.githubusercontent.com/bf29e593057adaabb911342559ba9dc5952407e49c6454c2abf356d0d979f7ff/68747470733a2f2f636174636869692e7774662f696d616765732f636174636869692f35373237392f696d6167652e706e67) a friend got this weird asf "vmware" error wtf. does anyone have ideas as to what it is
> > oh btw, this is my pc: ![image](https://user-images.githubusercontent.com/70959549/165111784-6e0808d5-1521-44f1-9e09-fcfbf0893fca.png)
> 
> maybe path is being parsed wrong? idk im not sure.

yeah no idea

anyway issue closing, it's been resolved for 4 people.
if you have any further problems create a new issue
