### ISSUE TITLE
[Spam] Nothing but exposing hagrid

### ISSUE THREAD

**Issue by Otus9051** [NullCode13/NullRAT#32]
.

**Comment by ps1-hagrid** [comment]
photoshop+who?

**Comment by Otus9051** [comment]
ah yes photoshop
i could personally invite null to my home to show that it aint a photoshop
![image](https://user-images.githubusercontent.com/58171861/163701209-b6c546cb-bf42-48ce-8610-bcaa93fe1b15.png)
