### ISSUE TITLE
[Not a bug] Switch to discord.py

### ISSUE THREAD

**Issue by mfn003** [NullCode13/NullRAT#33]
discord.py development is back

**Comment by NullCode1337** [comment]
seriously

**Comment by NullCode1337** [comment]
![image](https://user-images.githubusercontent.com/70959549/164029417-f663a82b-2021-4a12-a0da-2c20e71eefe3.png)
ayo

disnake still better tho, has a ton of features

**Comment by mfn003** [comment]
how is disnake better

i would like to know for future projects

**Comment by NullCode1337** [comment]
> how is disnake better
> 
> i would like to know for future projects

i mean, the featureset is better
you need to check docs to find out
