### ISSUE TITLE
compile..

### ISSUE THREAD

**Issue by kakakas33** [NullCode13/NullRAT#36]
INFO     ==================== Run command ====================
98 INFO: PyInstaller: 5.0
99 INFO: Python: 3.10.4
112 INFO: Platform: Windows-10-10.0.20348-SP0
option(s) not allowed:
  --onedir/--onefile
  --console/--nowindowed/--windowed/--noconsole
makespec options not valid when a .spec file is given
ERROR    Run command failed
The system cannot find the file specified.
Press any key to continue . . .

**Comment by NullCode1337** [comment]
tf

**Comment by NullCode1337** [comment]
hold on lemme test on my vm

**Comment by kakakas33** [comment]
the program crashes when I run the compiler on my own computer and select y/n. so I tried it on rdp and got this error.

**Comment by kakakas33** [comment]
> hold on lemme test on my vm

obfuscate is not work, i can compile with no obfuscate

**Comment by kakakas33** [comment]
Traceback (most recent call last):
  File "RAT.py", line 1, in <module>
ModuleNotFoundError: No module named 'Variables'

**Comment by NullCode1337** [comment]
> the program crashes when I run the compiler on my own computer and select y/n. so I tried it on rdp and got this error.

okay hold on, im beginning to see a lot of problems in @usrDottik code
for example, the dependencies installer doesnt work at all on my vm

**Comment by NullCode1337** [comment]
![image](https://user-images.githubusercontent.com/70959549/165035205-51b9e46a-2dcb-48e6-b54f-944ebf85faee.png)
yes brother, i have managed to recreate your issue
i will fix it asap

**Comment by NullCode1337** [comment]
issue has been fixed. if you have further problems please reply
