### ISSUE TITLE
NullRAT compiler is crashing

### ISSUE THREAD

**Issue by gumbobrot** [NullCode13/NullRAT#38]
I´ve done all preparing steps and I specified all the data (channel-ID, server-ID, etc) but when I open the NullRAT compiler and select everything NullRAT crashed when i try to compile the file.

**Comment by ghost** [comment]
> I´ve done all preparing steps and I specified all the data (channel-ID, server-ID, etc) but when I open the NullRAT compiler and select everything NullRAT crashed when i try to compile the file.

If your antivirus is enabled, disable it and try again

**Comment by NullCode1337** [comment]
> I´ve done all preparing steps and I specified all the data (channel-ID, server-ID, etc) but when I open the NullRAT compiler and select everything NullRAT crashed when i try to compile the file.

```
>run cmd
>cd "directory where the compiler is located"
>run NullRAT Compiler
```

you should be able to see the error in that case. send it here

**Comment by owoDennis911** [comment]
> > I´ve done all preparing steps and I specified all the data (channel-ID, server-ID, etc) but when I open the NullRAT compiler and select everything NullRAT crashed when i try to compile the file.
> 
> ```
> >run cmd
> >cd "directory where the compiler is located"
> >run NullRAT Compiler
> ```
> 
> you should be able to see the error in that case. send it here

i think i got this error
![image](https://user-images.githubusercontent.com/74814013/166084859-232fd7f8-f35a-429d-8e8c-36e67604dd76.png)

**Comment by NullCode1337** [comment]
> > > I´ve done all preparing steps and I specified all the data (channel-ID, server-ID, etc) but when I open the NullRAT compiler and select everything NullRAT crashed when i try to compile the file.
> > 
> > 
> > ```
> > >run cmd
> > >cd "directory where the compiler is located"
> > >run NullRAT Compiler
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > you should be able to see the error in that case. send it here
> 
> i think i got this error ![image](https://user-images.githubusercontent.com/74814013/166084859-232fd7f8-f35a-429d-8e8c-36e67604dd76.png)

Yeahhhh this thing also happened on a friend's PC
I told him to compile in a VM, and it worked.... So I thought it was a freak case

Man so I gotta test this issue now huh

**Comment by NullCode1337** [comment]
@owoDennis911 can you contact me on discord NullCode#1337
talking about issue on gh is  slow, real time better

**Comment by owoDennis911** [comment]
> NullCode#1337

added,Oh and i ran it in VM, \Common was unexpected at this time too

**Comment by NullCode1337** [comment]
![image](https://user-images.githubusercontent.com/70959549/166107217-0d0cc23e-02b5-4b03-b54a-4deaf3817c20.png)
issue fixed in vm
I'll research why it doesn't work in computers where language != english

**Comment by NullCode1337** [comment]
![image](https://user-images.githubusercontent.com/70959549/166140963-4bda9cc9-3094-493e-b88a-a7734235efaa.png)
Fixed compiler in main PC!!!!
issue was ching chong
