### ISSUE TITLE
Does not work at all

### ISSUE THREAD

**Issue by normaliok** [NullCode13/NullRAT#40]
I've created a bot and related blah-blah... Executed steps 1,2,3, but after start RAT.exe nothing is happing.

**Comment by NullCode1337** [comment]
blah blah blah is not a correct way to describe your issue
create a recording of what the fuck you're doing, if you're that lazy

**Comment by ArianFarrokhi** [comment]
> blah blah blah is not a correct way to describe your issue create a recording of what the fuck you're doing, if you're that lazy

XDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD

**Comment by NullCode1337** [comment]
issue inactive since last 4 days, closed.


> > blah blah blah is not a correct way to describe your issue create a recording of what the fuck you're doing, if you're that lazy
> 
> XDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD

lmao
