### ISSUE TITLE
[Inactive] Problem D:

### ISSUE THREAD

**Issue by ArianFarrokhi** [NullCode13/NullRAT#41]
Hey

so my problem is when i try to run a command it gets stuck on: (bot) is thinking...

![image](https://user-images.githubusercontent.com/80380401/169310993-2f73b5a4-25e2-44b7-b39d-4c8d843d4322.png)

**Comment by NullCode1337** [comment]
weird 
can you join the discord

**Comment by NullCode1337** [comment]
Issue inactive, didn't contact me on discord
Closed.
