### ISSUE TITLE
[idiot] number 1 reaason this will never work 

### ISSUE THREAD

**Issue by AstroOnYT** [NullCode13/NullRAT#42]
theres no persistence and all it takes for the user is to end the task in task manager. when the computer also is shut off it goes offline aswell so theres no point and theres no startup

**Comment by NullCode1337** [comment]
dude the /startup command exists LOL

**Comment by NullCode1337** [comment]
![image](https://user-images.githubusercontent.com/70959549/173308325-80288fee-178d-4d02-99bd-f1f8c6923ce9.png)
once you run this, rat will turn on every boot
