### ISSUE TITLE
[Finished] Send to all victims

### ISSUE THREAD

**Issue by StuKit** [NullCode13/NullRAT#48]
first of all, love your work man
secondly is there anyway to refer to every active victim as "all" when excuting a command, for exemple "/powershell all whoami"
sorry for my ignorance

**Comment by NullCode1337** [comment]
why not
i thought i added that already

**Comment by NullCode1337** [comment]
i was today years old when i realized it wasn't there.
thanks for the reminder I'll add it soon

**Comment by NullCode1337** [comment]
done! c1e1f1ed47109edf3dcdc93e7c9b922a2263349c
thanks for the feature ideas. keep em coming
