### ISSUE TITLE
What to do with discord?

### ISSUE THREAD

**Issue by BelleButCode** [NullCode13/NullRAT#50]
"Traceback (most recent call last):
  File "RAT.py", line 1, in <module>
ModuleNotFoundError: No module named 'Variables'"
I believe this is an issue caused by the fact that there is no particular prompting in the AOI. I don't know where to put the discord information either... Please help ;-;

**Comment by NullCode1337** [comment]
can you join my discord server and send a video? issue isn't clear

discord.gg/vr2gVjyuNv

**Comment by NullCode1337** [comment]
didnt send anything yet. issue closed due to inactivity
python installation guide coming soon
