### ISSUE TITLE
Add a keylogger (suggestion)

### ISSUE THREAD

**Issue by ghost** [NullCode13/NullRAT#55]
Hello ive been using this rat (for educational prouposes) and everything works great and all, but i think it would be great to add a keylogger.

You can use code from here https://github.com/Sp00p64/DiscordRAT/blob/master/DiscordRAT.py because this keylogger bypasses lots of anti malware solutions allready.

There are some things you gotta change if you want to use that code:
The stop command doesn't work.
You gotta make the keylog.txt file self destroy untill it reaches 8mb (so it can be uploaded to discord)

Keep up with the good work!

**Comment by NullCode1337** [comment]
keylogger detected af tho. im trying my best to look for some undetectable solutions
the currrent keyloggers written in C/Python dont cut it. too verbose

also big thanks for the appreciation. really helps my declining mental sanity
