### ISSUE TITLE
Pyinstaller Not Recognized as a command

### ISSUE THREAD

**Issue by SuNG0D** [NullCode13/NullRAT#56]
When I get to the "Are all these options correct?" and say yes, crash error shows up in cmd saying that pyinstaller is not reconginzable as an internal o external command. Need help ASAP

**Comment by ghost** [comment]
I can help you.
There are two methods:
![image](https://user-images.githubusercontent.com/97046121/200911621-18417270-7cbc-4ef0-894e-622ddb6276a7.png)
When installing python check the "Add python to environment variables"
OR:
you can go to your python scipts and find "pyinstaller.exe" and add it to your nullrat directory.

**Comment by ghost** [comment]
install it from python.org not from microsoft store.

**Comment by NullCode1337** [comment]
follow these ^^^

correct way to install python

**Comment by NullCode1337** [comment]
also issues been dead for 11 days id like to close

feel free to recomment
