### ISSUE TITLE
no commands

### ISSUE THREAD

**Issue by LSDJFIWNGW** [NullCode13/NullRAT#62]
i have seemingly set up the bot correctly, but no commands appear when i type a '/', only the in-built discord ones. I made sure that i put in the commands permission when creating the invite:
![image](https://user-images.githubusercontent.com/123031180/214404813-94872e0a-b867-4cca-a23c-bec711cf0409.png)
it also sends the notification that the rat has started on my pc, so i am a bit confused as to what i have done wrong.

**Comment by smthpy** [comment]
Refresh your discord client and you'll (most likely) be good to go

**Comment by NullCode1337** [comment]
you still having this issue? lmk

tbh I'm losing all motivation to work on nullrat, it's gotten seriously boring + no incentive on working in it

**Comment by smthpy** [comment]
Dang, that sucks. Let me know if you need anything man, I am willing to help if need be.

**Comment by NullCode1337** [comment]
> Dang, that sucks. Let me know if you need anything man, I am willing to help if need be.

nah its just that its boring, how long can a man work on a singular project
also its not like i make money out of it, instead of like a paid RAT

**Comment by ghost** [comment]
maybe start a paid version, and add some new features that make it worth buying that one. Writing open source software is awesome, but the money is a real problem.

**Comment by ghost** [comment]
> > Dang, that sucks. Let me know if you need anything man, I am willing to help if need be.
> 
> nah its just that its boring, how long can a man work on a singular project also its not like i make money out of it, instead of like a paid RAT

Hey, man, do you need donations?

I can donate a bit. I really loved this project and I want you to continue working on it. It's not like I cant make one of these, and I don't even use it anymore, but this is kind of nostalgic to me and really helped and motivated me in learning Python in the past.

If you need any help with anything tell me, i know how it feels not being motivated in a project.

**Comment by NullCode1337** [comment]
> > > Dang, that sucks. Let me know if you need anything man, I am willing to help if need be.
> > 
> > 
> > nah its just that its boring, how long can a man work on a singular project also its not like i make money out of it, instead of like a paid RAT
> 
> Hey, man, do you need donations?
> 
> I can donate a bit. I really loved this project and I want you to continue working on it. It's not like I cant make one of these, and I don't even use it anymore, but this is kind of nostalgic to me and really helped and motivated me in learning Python in the past.
> 
> If you need any help with anything tell me, i know how it feels not being motivated in a project.

thanks for the thought! i really appreciate it :)

But seriously though I wouldn't like to force anyone to pay for my rat etc, because it is still really immature and dumb + there are way better paid ones written in C/Rust

Also yup this is also my only project to reach this level of popularity, so it does hold a soft spot in my heart 
maybe I'll tinker with it some more after all
