### ISSUE TITLE
AIO does this 

### ISSUE THREAD

**Issue by Lent9000** [NullCode13/NullRAT#69]
Active code page: 65001
'30m═s not recognized as an internal or external command,
operable program or batch file.
's not recognized as an internal or external command,
operable program or batch file.
'ho' is not recognized as an internal or external command,
operable program or batch file.
'�████║██████╔╝██║' is not recognized as an internal or external command,
operable program or batch file.
'255m██╔═══╝' is not recognized as an internal or external command,
operable program or batch file.
'�██╗██████╗s not recognized as an internal or external command,
operable program or batch file.
'he' is not recognized as an internal or external command,
operable program or batch file.
'mpiler)' is not recognized as an internal or external command,
operable program or batch file.
'��███╔╝s not recognized as an internal or external command,
operable program or batch file.
'��║' is not recognized as an internal or external command,
operable program or batch file.
'�' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Lent9000** [comment]
Traceback (most recent call last):
  File "RAT.py", line 193, in <module>
  File "disnake\ext\commands\common_bot_base.py", line 521, in load_extension
disnake.ext.commands.errors.ExtensionNotFound: Extension 'rawTokens' could not be loaded.

**Comment by StuKit** [comment]
Had the same thing, imported every module manually and it works fine now, was a main, but worth it 👍

**Comment by NullCode1337** [comment]
> Active code page: 65001 '30m═s not recognized as an internal or external command, operable program or batch file. 's not recognized as an internal or external command, operable program or batch file. 'ho' is not recognized as an internal or external command, operable program or batch file. '�████║██████╔╝██║' is not recognized as an internal or external command, operable program or batch file. '255m██╔═══╝' is not recognized as an internal or external command, operable program or batch file. '�██╗██████╗s not recognized as an internal or external command, operable program or batch file. 'he' is not recognized as an internal or external command, operable program or batch file. 'mpiler)' is not recognized as an internal or external command, operable program or batch file. '��███╔╝s not recognized as an internal or external command, operable program or batch file. '��║' is not recognized as an internal or external command, operable program or batch file. '�' is not recognized as an internal or external command, operable program or batch file.

your OS probably doesnt support custom encoding, use AIO legacy

**Comment by ptrprkr** [comment]
> Had the same thing, imported every module manually and it works fine now, was a main, but worth it 👍

How do you import the modules manually? Sorry for a 2nd question

**Comment by NullCode1337** [comment]
Try the new compiler on NullRAT X
Re open if any further problems
