### ISSUE TITLE
[Self-solved] /get_webcam command doesnt work

### ISSUE THREAD

**Issue by gurubyte** [NullCode13/NullRAT#70]
It says:

`This site can’t be reached. The webpage at https://cdn.discordapp.com/attachments/XXXXXXXXXXXX/XXXXXXXXXXXXXX/image.png might be temporarily down or it may have moved permanently to a new web address.`

**Comment by NullCode1337** [comment]
well, figured this would happen eventually...
the image is actually a bmp file that i renamed to png to bypass discord restrictions, i guess its patched now

**Comment by NullCode1337** [comment]
im working on getting the webcam and everything sorted

**Comment by gurubyte** [comment]
hey, it works now! :) at least for me

**Comment by NullCode1337** [comment]
> hey, it works now! :) at least for me

oh woah, i didnt even do anything ;)
thanks for reporting. closing issue.
