### ISSUE TITLE
[Solved] Pyarmor failure upon compile

### ISSUE THREAD

**Issue by sudOcrypt** [NullCode13/NullRAT#71]
1 file(s) copied.
modules\checkedtokens.py
modules\clipboard.py
modules\directory.py
modules\geolocate.py
modules\getenv.py
modules\hide.py
modules\placeholder.py
modules\rawtokens.py
modules\receivefiles.py
modules\runfile.py
modules\screenshot.py
modules\sendfiles.py
modules\shell.py
modules\startup.py
modules\systeminfo.py
modules\tasklist.py
modules\webcam.py
modules\wifi.py
        1 file(s) copied.
152 INFO: PyInstaller: 4.10
152 INFO: Python: 3.8.10
157 INFO: Platform: Windows-10-10.0.19045-SP0
158 INFO: wrote C:\Users\J\Downloads\NullRAT\compiling-16113\RAT.spec
158 INFO: UPX is not available.
script 'C:\Users\J\Downloads\NullRAT\compiling-16113\RAT.py' not found
The system cannot find the file specified.

Waiting for 0

**Comment by NullCode1337** [comment]
problem with pyarmor.
checking....
for now disable pyarmor option in compiler, it will work

**Comment by NullCode1337** [comment]
latest compiler should fix this issue
please try again!

if issue persists feel free to open another issue
