### ISSUE TITLE
Compiling error when installing dependencies

### ISSUE THREAD

**Issue by samn47** [NullCode13/NullRAT#77]
[1] Checking for Python...
Python 3.11.0
Python 3.11.0
- Python installed!

[2] Checking if packages already installed...
Some dependencies are not installed!
Some dependencies are not installed!
Some dependencies are not installed!
Some dependencies are not installed!
Some dependencies are not installed!
[3] Installing/Updating dependencies...
ERROR: Ignored the following versions that require a different python version: 4.10 Requires-Python <3.11,>=3.6; 4.6 Requires-Python <3.11,>=3.6; 4.7 Requires-Python <3.11,>=3.6; 4.8 Requires-Python <3.11,>=3.6; 4.9 Requires-Python <3.11,>=3.6; 5.0 Requires-Python <3.11,>=3.7; 5.0.1 Requires-Python <3.11,>=3.7; 5.1 Requires-Python <3.11,>=3.7; 5.2 Requires-Python <3.11,>=3.7; 5.3 Requires-Python <3.11,>=3.7; 5.4 Requires-Python <3.11,>=3.7; 5.4.1 Requires-Python <3.11,>=3.7
ERROR: Could not find a version that satisfies the requirement pyinstaller==4.10 (from versions: 2.0, 2.1, 3.0, 3.1, 3.1.1, 3.2, 3.2.1, 3.3, 3.3.1, 3.4, 3.5, 3.6, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.5.1, 5.5, 5.6, 5.6.1, 5.6.2, 5.7.0, 5.8.0, 5.9.0, 5.10.0, 5.10.1, 5.11.0, 5.12.0, 5.13.0, 5.13.1, 5.13.2, 6.0.0, 6.1.0, 6.2.0, 6.3.0, 6.4.0)
ERROR: No matching distribution found for pyinstaller==4.10

**Comment by NullCode1337** [comment]
your Python version is too new, uninstall it

a option should come in NullRAT to auto install a recommended Python version, do that
