### ISSUE TITLE
error while running

### ISSUE THREAD

**Issue by TahaAzhar36** [NullCode13/NullRAT#9]
Traceback (most recent call last):
  File "C:\Users\TaHa\Downloads\Compressed\NullRAT-5.0\NullRAT-5.0\src\RAT.py", line 14, in <module>
    client       = discord.Bot()
AttributeError: module 'discord' has no attribute 'Bot'

**Comment by NullCode1337** [comment]
uninstall discord.py/any other discord module, and run the installer again.
if it doesn't work, let me know

**Comment by NullCode1337** [comment]
try the new zips posted in Releases
